import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

interface RequestBody {
  youtubeUrl: string;
}

Deno.serve(async (req: Request) => {
  // 1. Handle CORS preflight
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    // 2. Validate user authentication
    const authHeader = req.headers.get("Authorization");
    if (!authHeader || !authHeader.startsWith("Bearer ")) {
      return new Response(
        JSON.stringify({ error: "Authentication required. Please sign in to generate transcripts." }),
        { status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const supabaseUrl = Deno.env.get("SUPABASE_URL") ?? "";
    const supabaseAnonKey = Deno.env.get("SUPABASE_ANON_KEY") ?? "";
    const supabase = createClient(supabaseUrl, supabaseAnonKey, {
      global: { headers: { Authorization: authHeader } },
    });

    const { data: { user }, error: authError } = await supabase.auth.getUser();
    if (authError || !user) {
      return new Response(
        JSON.stringify({ error: "Invalid or expired session. Please sign in again." }),
        { status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // 3. Parse and validate body
    let body: RequestBody;
    try {
      body = await req.json();
    } catch {
      return new Response(
        JSON.stringify({ error: "Invalid request payload." }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const { youtubeUrl } = body;
    if (!youtubeUrl || typeof youtubeUrl !== "string") {
      return new Response(
        JSON.stringify({ error: "A valid YouTube URL is required." }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Simple URL validation
    const youtubeRegex = /^(https?:\/\/)?(www\.)?(youtube\.com\/(watch\?v=|embed\/|shorts\/)|youtu\.be\/)[\w-]{11}(.*)?$/i;
    if (!youtubeRegex.test(youtubeUrl.trim())) {
      return new Response(
        JSON.stringify({ error: "Please enter a valid YouTube video link." }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // 4. Apify Actor Token (Server-side secret only)
    const apifyToken = Deno.env.get("APIFY_API_TOKEN");
    if (!apifyToken || apifyToken.trim() === "") {
      return new Response(
        JSON.stringify({
          error: "APIFY_API_TOKEN is not configured on the server. Please set the APIFY_API_TOKEN secret in your Supabase project settings under Edge Functions -> Secrets.",
        }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // 5. Trigger Apify Actor: streamers/youtube-scraper
    const apifyUrl = `https://api.apify.com/v2/acts/streamers~youtube-scraper/run-sync-get-dataset-items?token=${apifyToken.trim()}`;
    
    const apifyInput = {
      startUrls: [{ url: youtubeUrl.trim() }],
      maxResults: 1,
      transcriptionAndSubtitle: "ALWAYS_SUBTITLES",
      downloadSubtitles: true,
      subtitlesLanguage: "any",
      subtitlesFormat: "plaintext",
      preferAutoGeneratedSubtitles: true,
    };

    console.log(`Starting Apify scraping for video: ${youtubeUrl} for user: ${user.id}`);

    const apifyResponse = await fetch(apifyUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(apifyInput),
    });

    if (!apifyResponse.ok) {
      const errText = await apifyResponse.text();
      console.error("Apify actor run failed:", apifyResponse.status, errText);
      return new Response(
        JSON.stringify({ error: "Apify transcription service error. Please try again in a few moments." }),
        { status: 502, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const items = await apifyResponse.json();

    if (!Array.isArray(items) || items.length === 0) {
      return new Response(
        JSON.stringify({ error: "No video details could be extracted for this YouTube URL." }),
        { status: 404, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const videoItem = items[0];

    // Check if scraper returned an error item
    if (videoItem.error) {
      let friendlyError = "Unable to process video: " + videoItem.error;
      if (videoItem.error === "VIDEO_UNAVAILABLE") friendlyError = "This YouTube video is unavailable, deleted, or region-restricted.";
      if (videoItem.error === "AGE_RESTRICTED") friendlyError = "This YouTube video is age-restricted and cannot be processed.";
      if (videoItem.error === "NOT_FOUND") friendlyError = "YouTube video not found. Please verify the URL.";
      
      return new Response(
        JSON.stringify({ error: friendlyError }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // 6. Extract Subtitles / Transcript
    let transcriptText = "";
    if (Array.isArray(videoItem.subtitles) && videoItem.subtitles.length > 0) {
      // Find English first, or take the first available subtitle
      const enSub = videoItem.subtitles.find((s: any) => s.language === "en" || s.language === "any");
      const chosenSub = enSub || videoItem.subtitles[0];
      transcriptText = chosenSub.plaintext || chosenSub.srt || "";
    }

    // If still empty, check if speech-to-text transcriptionUrl is present
    if (!transcriptText.trim() && videoItem.transcriptionUrl) {
      try {
        const transRes = await fetch(videoItem.transcriptionUrl);
        if (transRes.ok) {
          transcriptText = await transRes.text();
        }
      } catch (err) {
        console.warn("Failed to fetch transcriptionUrl:", err);
      }
    }

    if (!transcriptText.trim()) {
      return new Response(
        JSON.stringify({
          error: "No transcript or subtitles could be found for this video. Please ensure the video has closed captions or spoken audio enabled.",
        }),
        { status: 422, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Clean up transcript text:
    // Remove artificial single newlines from subtitle cues so words flow naturally into full-width sentences
    const rawCleaned = transcriptText
      .replace(/\r\n/g, "\n")
      .replace(/([^\n])\n([^\n])/g, "$1 $2")
      .replace(/\s{2,}/g, " ")
      .trim();

    // Generate natural readable paragraphs (~75 words per paragraph)
    const words = rawCleaned.split(/\s+/).filter(Boolean);
    const PARAGRAPH_WORD_COUNT = 75;
    const segments: Array<{ id: string; timestamp: string; seconds: number; speaker: string; text: string }> = [];

    if (words.length <= PARAGRAPH_WORD_COUNT) {
      segments.push({
        id: "seg-1",
        timestamp: "00:00",
        seconds: 0,
        speaker: videoItem.channelName || "Speaker",
        text: rawCleaned,
      });
    } else {
      for (let i = 0; i < words.length; i += PARAGRAPH_WORD_COUNT) {
        const chunkWords = words.slice(i, i + PARAGRAPH_WORD_COUNT);
        const chunkText = chunkWords.join(" ");
        const totalSecs = Math.round((i / words.length) * 180);
        const mins = Math.floor(totalSecs / 60);
        const secs = totalSecs % 60;
        const formattedTimestamp = `${String(mins).padStart(2, "0")}:${String(secs).padStart(2, "0")}`;

        segments.push({
          id: `seg-${Math.floor(i / PARAGRAPH_WORD_COUNT) + 1}`,
          timestamp: formattedTimestamp,
          seconds: totalSecs,
          speaker: videoItem.channelName || "Speaker",
          text: chunkText,
        });
      }
    }

    const cleanText = segments.map((s) => s.text).join("\n\n");
    const wordCount = words.length;
    const characterCount = cleanText.length;

    // Build structured response
    const resultData = {
      video: {
        id: videoItem.id || "video",
        url: youtubeUrl.trim(),
        title: videoItem.title || "YouTube Video",
        channel: videoItem.channelName || "YouTube Channel",
        duration: videoItem.duration || "N/A",
        wordCount,
        characterCount,
        thumbnailUrl: videoItem.thumbnailUrl || "",
        publishedDate: videoItem.date || "Recently",
      },
      segments,
      fullText: cleanText,
    };

    return new Response(
      JSON.stringify({ success: true, data: resultData }),
      { status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (err: any) {
    console.error("Unexpected error in generate-transcript function:", err);
    return new Response(
      JSON.stringify({ error: err?.message || "Internal server error while generating transcript." }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
